services:
  ssti-challenge:
    build: .
    ports:
      - "7000:7000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - SECRET_KEY=flask_app_secret_2024
      - FLAG=FLAG{ssti_template_injection_discovered}
      - DATABASE_URL=sqlite:///marketing.db
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ssti-network

networks:
  ssti-network:
    driver: bridge
